/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo.submodule.app

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testApp() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.lib, "app should have a lib")
        assertNotNull(classUnderTest.svc1, "app should have a svc1")
        assertNotNull(classUnderTest.svc2, "app should have a svc2")
    }
}
